In [1]:
import pandas as pd

In [2]:
risk=pd.read_csv("Lifestyle_and_Health_Risk_Prediction_Synthetic_Dataset (1).csv")
df=pd.DataFrame(risk)

In [3]:
df.columns

Index(['age', 'weight', 'height', 'exercise', 'sleep', 'sugar_intake',
       'smoking', 'alcohol', 'married', 'profession', 'bmi', 'health_risk'],
      dtype='object')

In [4]:
df.shape

(5000, 12)

In [5]:
df.describe()

               age       weight       height        sleep         bmi
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.00000
mean     48.805600    77.359200   171.933200     6.997060    26.84388
std      17.906991    18.714567    15.822225     1.432849     8.25249
min      18.000000    45.000000   145.000000     3.000000    11.40000
25%      34.000000    61.000000   158.000000     6.000000    20.30000
50%      49.000000    77.000000   171.500000     7.000000    26.00000
75%      64.000000    94.000000   186.000000     8.000000    32.40000
max      79.000000   109.000000   199.000000    10.000000    51.40000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           5000 non-null   int64
 1   weight        5000 non-null   int64
 2   height        5000 non-null   int64
 3   exercise      5000 non-null   object
 4   sleep         5000 non-null   float64
 5   sugar_intake  5000 non-null   object
 6   smoking       5000 non-null   object
 7   alcohol       5000 non-null   object
 8   married       5000 non-null   object
 9   profession    5000 non-null   object
 10  bmi           5000 non-null   float64
 11  health_risk   5000 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 468.9+ KB

In [7]:
df.isna().sum()
#missing values
# ===============
# fillna() is used to fill the missing values
# df["age"].fillna(df["age"].mean())    >>numerical
# df["age"].fillna(df["age"].median())  >>numerical
# df["exercise"].fillna(df["exercise"].mode())    >>string
# to fill missing NaN values with the mode(the most frequent value)

age             0
weight          0
height          0
exercise        0
sleep           0
sugar_intake    0
smoking         0
alcohol         0
married         0
profession      0
bmi             0
health_risk     0
dtype: int64

In [8]:
X=df.drop("health_risk",axis=1)
y=df["health_risk"]

In [9]:
X.dtypes

age               int64
weight            int64
height            int64
exercise         object
sleep           float64
sugar_intake     object
smoking          object
alcohol          object
married          object
profession       object
bmi             float64
dtype: object

In [10]:
# Encoding >>> converting the string values in X into numerical values
# the column profession has multiple values so we are choosing one-hot encoding
# one-hot encoding takes each profession from profession column and coverts to 0 or 1 
# for all the rows by adding new columns for each profession

X=pd.get_dummies(X)
X

,age,weight,height,sleep,bmi,exercise_high,exercise_low,exercise_medium,exercise_none,sugar_intake_high,...,married_no,married_yes,profession_artist,profession_doctor,profession_driver,profession_engineer,profession_farmer,profession_office_worker,profession_student,profession_teacher
0,56,67,195,6.1,17.6,False,True,False,False,False,...,False,True,False,False,False,False,False,True,False,False
1,69,76,170,6.9,26.3,True,False,False,False,True,...,True,False,False,False,False,False,False,False,False,True
2,46,106,153,6.6,45.3,True,False,False,False,False,...,True,False,True,False,False,False,False,False,False,False
3,32,54,186,8.5,15.6,False,False,True,False,False,...,True,False,True,False,False,False,False,False,False,False
4,60,98,195,8.0,25.8,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,42,75,187,7.2,21.4,False,False,True,False,False,...,False,True,False,False,True,False,False,False,False,False
4996,39,86,183,7.4,25.7,False,True,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4997,48,56,194,7.2,14.9,False,False,False,True,True,...,False,True,False,False,False,True,False,False,False,False
4998,34,109,148,9.9,49.8,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
4999,72,47,149,6.3,21.2,True,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [12]:
# weight>>
# age>>
# height>>

# Feature scaling
# ==================
# feature scaling in machine learning is the process of changing numerical
# columns to use the same value range

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
# scaler.fit(X_train)mean+std
# scaler.transform(X_train)
# OR TOGETHER
X_train=scaler.fit_transform(X_train)#need to fit before transform for X_train
X_test=scaler.transform(X_test)# X_test should not be given in fit()
# if we allow to fit X_test it may lead to data leakage
# fit():Learns and stores stats like the mean and standard deviation from your dataset,
# but does not change the data
# transfrom():Uses the pre calculated stats to scale or change the data

In [17]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8266666666666667